# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Karolina Finc
tagline:          'Cognitive Neuroscientist'
description:      'Neuroplasticity. Network neuroscience. Neuroimaging. Consciousness. Reinforcement learning.'
url:              https://kfinc.github.io/
baseurl:          /

author:
  name:           'Karolina Finc'
  url:            https://twitter.com/karofinc

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kfinc
